/*
  THIS FILE WAS AUTOGENERATED BY mode.tmpl.js
*/

import { inherits } from "../lib/oop.js";
import { Mode as TextMode } from "./text.js";
import { ActionScriptHighlightRules } from "./actionscript_highlight_rules.js";
import { FoldMode } from "./folding/cstyle.js";

export class Mode {
  constructor() {
    this.HighlightRules = ActionScriptHighlightRules;
    this.foldingRules = new FoldMode();
    this.$behaviour = this.$defaultBehaviour;
  }
};
inherits(Mode, TextMode);

(function() {
    this.lineCommentStart = "//";
    this.blockComment = {start: "/*", end: "*/"};
    this.$id = "ace/mode/actionscript";
    this.snippetFileId = "ace/snippets/actionscript";
}).call(Mode.prototype);